name: SFTR
title: Latest at SFTR
description: News at the club
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ''
google_analytics: UA-xxxxxxxx-1
disqus: demowebsite
mailchimp-list: >-
  https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
  - _pages
permalink: '/:title/'
email: wowthemesnet@gmail.com
authors:
  angela:
    name: angela
    display_name: Angela
    avatar: assets/images/avatar-sal.png
    email: wowthemesnet@gmail.com
    web: 'https://www.wowthemes.net/donate/'
    twitter: 'https://twitter.com/wowthemesnet'
    description: >-
      Resident link and content developer
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: disabled
authorbox: enabled
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
url: ''
